# Generated by Django 5.0.6 on 2024-05-25 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mango',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variety', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('images', models.ImageField(upload_to='mangoes/')),
                ('video', models.URLField(blank=True, null=True)),
                ('taste_review', models.TextField(blank=True, null=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mango', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.mango')),
            ],
        ),
        migrations.CreateModel(
            name='TreeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('variety', models.CharField(max_length=100)),
                ('fertilizer_used', models.TextField(blank=True, null=True)),
                ('tree_images', models.ImageField(blank=True, null=True, upload_to='trees/')),
                ('pesticide_used', models.BooleanField(default=False)),
                ('tree_video', models.URLField(blank=True, null=True)),
                ('mango', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='marketplace.mango')),
            ],
        ),
    ]
